console.log("helooooooooooo");
console.log("44");
var fullname ="so nguoi";
let job ="an trom";
const age=20;
confirm("xin chao");
var a =prompt("nhap a");
var b =parseInt(prompt("nhap b"));
var tong  = a + b ;
console.log(tong);
//var a =" Alooooo abc abc";
//var b = 'Xin chao ABC ABC ';
//console.log(a);
//console.log(b);
//console.log(a + " " + b);
//var fname ="anh quan";
//console.log(`xin chao toi ten la ${fname}, toi bi nghien`);
